---
title: "DataExploration"
output: html_notebook
editor_options: 
  chunk_output_type: console
---


```{r}
#install.packages('agridat') 
library(agridat)
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(cowplot)
library(smooth)
library(kableExtra)
library(readxl)
```


```{r}
soybean <- read_excel("data/HUSSoyb.xls", sheet = 'cleaned')

```



Exploring Data
```{r}


soybean <- soybean %>% 
  group_by(year) %>% 
  summarise(yield = mean(yield))



n_for <- round(nrow(soybean) * .10)
nobs <- nrow(soybean)
nvar <- ncol(soybean)



plot <- ggplot(soybean) + 
  geom_line(aes(x = year, y = yield))
```


```{r}
ts_soybean_full <- ts(soybean$yield,
                      start = soybean$year[1],
                      frequency = 1)

ts_soybean_test <- ts(soybean$yield[(nobs-n_for+1):nobs],
                      start = soybean$year[nobs-n_for+1],
                      frequency = 1)

ts_soybean_train <- ts(soybean$yield[1:(nobs-n_for)],
                 start = soybean$year[1],
                 frequency = 1)

ts_soybean_log_full <- ts(log(soybean$yield),
                      start = soybean$year[1],
                      frequency = 1)

ts_soybean_log_test <- ts(log(soybean$yield[(nobs-n_for+1):nobs]),
                      start = soybean$year[nobs-n_for+1],
                      frequency = 1)

ts_soybean_log_train <- ts(log(soybean$yield[1:(nobs-n_for)]),
                 start = soybean$year[1],
                 frequency = 1)

```



Plotting Data
```{r}
theme_set(theme_classic())

ts <- autoplot(ts_soybean_full, plot = FALSE, ylab = "Yield (bu./acre)")

pacf <- autoplot(Pacf(ts_soybean_full, lag = 40, plot=FALSE),  
                  main = "PACF of Yield")

acf <- autoplot(Acf(ts_soybean_full, lag = 40, plot=FALSE),  
                  main = "ACF of Yield")

ggsave("data/soy_ts.png", plot = ts)
ggsave("data/soy_pacf.png", plot = pacf)
ggsave("data/soy_acf.png", plot = acf)

plot_grid(ts, pacf, acf,
          nrow = 3)
```



Stationary Test
```{r}
print((adf.test(ts_soybean_full,alternative="stationary")))
#P value greater than .05 so we faill to reject H0, data has stochastic trend

```


```{r}

t <- c(1:nobs)

linear_trend_model <- lm(ts_soybean_full ~ t )
beta0 <- as.numeric(linear_trend_model$coefficients[1])
beta1 <- as.numeric(linear_trend_model$coefficients[2])

linear_trend <- beta0 + beta1 * t
ts_linear <- ts(linear_trend, start = 1924, frequency = 1)

detrend <- soybean$yield - linear_trend
ts_detrend <- ts(detrend, start = 1924, frequency = 1)

autoplot(ts_soybean_full) +
    autolayer(ts_linear) +
    autolayer(ts_detrend)
```


```{r}
ts_soybean_detrend_train <- ts(detrend[1:(nobs-n_for)],
                 start = soybean$year[1],
                 frequency = 1)

ts_soybean_detrend_test <- ts(detrend[(nobs-n_for+1):length(detrend)],
                      start = soybean$year[nobs-n_for+1],
                      frequency = 1)

```


```{r}
ts <- autoplot(ts_detrend, plot = FALSE)

pacf <- autoplot(Pacf(ts_detrend, lag = 40, plot=FALSE),  
                  main = "PACF")

acf <- autoplot(Acf(ts_detrend, lag = 40, plot=FALSE),  
                  main = "ACF")

plot_grid(ts, pacf, acf,
          nrow = 3
)
```


Forecasting Simple Techniques
```{r}

#simple moving average
sma_soy <- sma(y = ts_soybean_full, h = n_for, holdout = FALSE, silent = FALSE)

#simple exponential smoothing
ses_soy <- ses(y = ts_soybean_full, h = n_for, holdout = FALSE, silent = FALSE)

#auto sarima
sarima_soy <- auto.arima(ts_soybean_train)
sarima_forecast <- forecast(object = sarima_soy, h = n_for)

checkresiduals(sarima_forecast)
sarima_residuals <- autoplot(sarima_forecast$residuals, ylab = "", main = "Residuals")


sarima_scores <- accuracy(sarima_forecast$mean, ts_soybean_test)
sma_scores <- accuracy(sma_soy$forecast, ts_soybean_test)
ses_scores <- accuracy(ses_soy$mean, ts_soybean_test)



```


BATS

```{r}
TBATS_fit <- tbats(ts_soybean_train)
TBATS_forecast <- forecast(TBATS_fit, h = n_for)

soy_bats <- autoplot(TBATS_forecast, ylab = "Yield") + 
  autolayer(ts_soybean_test, series = "Test Dataset")

TBATS_scores <- accuracy(TBATS_forecast$mean, ts_soybean_test)

```




Neural Network

```{r}

NN_fit <- nnetar(ts_soybean_train,
                 P = 0,
                 p = 5)
                
NN_forecast <- forecast(NN_fit,
                        h = n_for) 

NN_scores <- accuracy(NN_forecast$mean, ts_soybean_test)

```


State space exponential smoothing
```{r}
SSES_fit <- es(ts_soybean_train, model = "ZZZ", h = n_for, holdout = FALSE)
SSES_forecast <- forecast(SSES_fit, h = n_for)

checkresiduals(SSES_fit)

SSES_scores <- accuracy(SSES_forecast, ts_soybean_test)



StructTS_fit <- StructTS(ts_soybean_train,
                   type = "trend")
StructTS_forecast <- forecast(StructTS_fit, h = n_for)

checkresiduals(StructTS_fit)

StructTS_scores <- accuracy(StructTS_forecast$mean, ts_soybean_test)

```

```{r}

autoplot(ts_soybean_train) +
  autolayer(sma_soy$forecast, series = "Simple Moving Average") +
  autolayer(ses_soy$mean, series = "Simple Exponential Smoothing") +
  autolayer(sarima_forecast$mean, series = "ARIMA(3,1,0)") +
  autolayer(TBATS_forecast$mean, series = "TBATS") +
  autolayer(NN_forecast$mean, series = "NNAR(5,3)") +
  autolayer(SSES_forecast$mean, series = "ETS(AAN)") +
  autolayer(StructTS_forecast$mean, series = "Structual TS")
  
```



```{r}
#edit to include all
#create data frame
soy_scores <- as.data.frame(rbind(NN_scores, sarima_scores, StructTS_scores, TBATS_scores, SSES_scores, ses_scores, sma_scores))
row.names(soy_scores) <- c("NNAR(5,3)", "ARIMA(3,1,0)","Structural TS", "TBATS", "ETS(AAN)", "SES", "SMA")

#choose model with lowest RMSE
best_model_index <- which.min(soy_scores[,"RMSE"])
cat("The best model by RMSE is:", row.names(soy_scores[best_model_index,]))       

scores <- kbl(soy_scores, 
      caption = "Forecast Accuracy for Soybean Models",
      digits = array(5,ncol(soy_scores))) %>%
  kable_styling(full_width = FALSE, position = "center") %>%
  #highlight model with lowest RMSE
  kable_styling(latex_options="striped", stripe_index = which.min(soy_scores[,"RMSE"]))


```



