---
title: "Corn Forecasting"
output: html_notebook
editor_options: 
  chunk_output_type: console
---


```{r}
library(agridat)
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(cowplot)
library(smooth)
library(kableExtra)

```

Exploring Data
```{r}

corn <- nass.corn
corn$bushels <- corn$acres * corn$yield
aggregated_corn <- corn %>%
  group_by(year) %>%
  summarise(total_bushels = sum(bushels), total_acreage = sum(acres))

aggregated_corn$total_yield <- aggregated_corn$total_bushels / aggregated_corn$total_acreage

yield_ts <- ts(aggregated_corn$total_yield, start=aggregated_corn$year[1], frequency = 1)
yield_plot <- autoplot(yield_ts)+ylab("Corn Yield (Bushels/Acre)")+ggtitle("US Corn Yield (1866-2011)")
yield_plot

acreage_ts <- ts(aggregated_corn$total_acreage, start=aggregated_corn$year[1], frequency = 1)
autoplot(acreage_ts)

# Reserve ~10% data for testing
nobs <- nrow(aggregated_corn)
nobs_test <- nobs %/% 10
nobs <- nobs - nobs_test
corn_training_data <- aggregated_corn[1:nobs,]
corn_test_data <- aggregated_corn[(nobs+1) : nrow(aggregated_corn),]

yield_training_ts <- ts(corn_training_data$total_yield, start=corn_training_data$year[1], frequency = 1)
yield_test_ts <- ts(corn_test_data$total_yield, start=corn_test_data$year[1], frequency = 1)

```


ACF/PACF
```{r}
acf <- autoplot(Acf(yield_ts, lag = 40, plot=FALSE),  
                  main = "ACF")

pacf <- autoplot(Pacf(yield_ts, lag = 40, plot=FALSE),  
                  main = "PACF")

plot_grid(yield_plot, pacf, acf,
          nrow = 3
)
```

Stationary Test
```{r}
print((adf.test(yield_ts,alternative="stationary")))
# p value = 0.99, so we fail to reject H0, data has stochastic trend

diff_yield <- diff(yield_ts)
print((adf.test(diff_yield,alternative="stationary")))


```

Forecasting Simple Techniques
```{r}
naive_corn <- naive(yield_training_ts, h = nobs_test)
plot(naive_corn)

#simple moving average
sma_corn <- sma(y = yield_training_ts, h = nobs_test, holdout = FALSE, silent = FALSE)
plot(sma_corn)

#simple exponential smoothing
ses_corn <- ses(y = yield_training_ts, h = nobs_test, holdout = FALSE, silent = FALSE)
autoplot(ses_corn)

plot(yield_ts, col = 'black')
lines(ses_corn$fitted, col = 'blue')
lines(ses_corn$mean, col = 'blue')

#auto sarima
sarima_corn <- auto.arima(yield_training_ts)
print(sarima_corn)

sarima_forecast <- forecast(object = sarima_corn, h = nobs_test)
checkresiduals(sarima_forecast)
autoplot(sarima_forecast)+ylab("Corn Yield")


```


Advanced techniques

State space exponential smoothing
```{r}
SSES_corn <- es(yield_training_ts, model = "ZZZ", h = nobs_test, holdout = FALSE)
sses_forecast <- forecast(SSES_corn, h=nobs_test)
plot(sses_forecast)
checkresiduals(SSES_corn)

plot(yield_ts, col = 'black')
lines(SSES_corn$fitted, col = 'blue')
lines(SSES_corn$forecast, col = 'blue')

```


Checking accuracy
```{r}
naive_accuracy <- accuracy(naive_corn$mean, yield_test_ts)
sma_accuracy <- accuracy(sma_corn$forecast, yield_test_ts)
ses_accuracy <- accuracy(ses_corn, yield_test_ts)

sarima_accuracy <- accuracy(sarima_forecast, yield_test_ts)
sarima_accuracy

sses_accuracy <- accuracy(SSES_corn$forecast, yield_test_ts)


# collect into one df
accuracy_df <- bind_rows(
  as.data.frame(t(naive_accuracy["Test set", c("RMSE", "MAE", "MPE", "MAPE")])),
  as.data.frame(t(sma_accuracy["Test set", c("RMSE", "MAE", "MPE", "MAPE")])),
  as.data.frame(t(ses_accuracy["Test set", c("RMSE", "MAE", "MPE", "MAPE")])),
  as.data.frame(t(sarima_accuracy["Test set", c("RMSE", "MAE", "MPE", "MAPE")])),
  as.data.frame(t(sses_accuracy["Test set", c("RMSE", "MAE", "MPE", "MAPE")]))
)
accuracy_df$Model <- c("Naive", "SMA", "SES", "ARIMA", "SS Exp. Smoothing")
accuracy_df <- accuracy_df[, c("Model", "RMSE", "MAE", "MPE", "MAPE")]

accuracy_df

```




